jerm_bundle_data_index:
    path: /di/{entity}/{column_preset}/{filter_preset}
    controller: Musicjerm\Bundle\JermBundle\Controller\BaseController::indexAction
    defaults:
        column_preset: -1
        filter_preset: -1

jerm_bundle_data_columns:
    path: /data/columns/{entity}/{column_preset}
    controller: Musicjerm\Bundle\JermBundle\Controller\BaseController::dataColumnsAction
    defaults:
        column_preset: -1

jerm_bundle_data_query:
    path: /data/query/{entity}/{column_preset}
    controller: Musicjerm\Bundle\JermBundle\Controller\BaseController::dataQueryAction
    defaults:
        column_preset: -1

jerm_bundle_data_column_config_create:
    path: /data/column/config/create/{entity}/{id}
    controller: Musicjerm\Bundle\JermBundle\Controller\BaseController::dataConfigCreateAction
    defaults:
        id: -1

jerm_bundle_data_column_config_update:
    path: /data/column/config/update/{entity}/{id}
    controller: Musicjerm\Bundle\JermBundle\Controller\BaseController::dataConfigUpdateAction

jerm_bundle_data_column_config_delete:
    path: /data/column/config/delete/{entity}/{id}
    controller: Musicjerm\Bundle\JermBundle\Controller\BaseController::dataConfigDeleteAction

jerm_bundle_data_filters_create:
    path: /data/filters/create/{entity}
    controller: Musicjerm\Bundle\JermBundle\Controller\FiltersController::createAction

jerm_bundle_data_filter_preset_update:
    path: /data/filters/update/{entity}/{id}
    controller: Musicjerm\Bundle\JermBundle\Controller\FiltersController::updateAction

jerm_bundle_data_filter_preset_delete:
    path: /data/filters/delete/{id}
    controller: Musicjerm\Bundle\JermBundle\Controller\FiltersController::deleteAction

jerm_bundle_data_get_csv:
    path: /data/get_csv/{entity}/{column_preset}/{filter_preset}
    controller: Musicjerm\Bundle\JermBundle\Controller\BaseController::getCsvAction
    defaults:
        column_preset: -1
        filter_preset: -1

jerm_bundle_api_data_get_csv:
    path: /api/get_csv/{entity}/{column_preset}/{filter_preset}
    controller: Musicjerm\Bundle\JermBundle\Controller\BaseController::getCsvAction
    defaults:
        column_preset: -1
        filter_preset: -1

jerm_bundle_crud_create:
    path: /crud/create/{entity}
    controller: Musicjerm\Bundle\JermBundle\Controller\CRUDController::createAction

jerm_bundle_crud_update:
    path: /crud/update/{entity}/{id}
    controller: Musicjerm\Bundle\JermBundle\Controller\CRUDController::updateAction

jerm_bundle_crud_delete:
    path: /crud/delete/{entity}
    controller: Musicjerm\Bundle\JermBundle\Controller\CRUDController::deleteAction

jerm_bundle_subscriber_create:
    path: /subscriber/create/{entity}/{id}
    controller: Musicjerm\Bundle\JermBundle\Controller\SubscriberController::createAction

jerm_bundle_subscriber_batch:
    path: /subscriber/batch/{entity}
    controller: Musicjerm\Bundle\JermBundle\Controller\SubscriberController::batchAction

jerm_bundle_get_file:
    path: /crud/get_file/{entity}/{id}
    controller: Musicjerm\Bundle\JermBundle\Controller\CRUDController::getFileAction

jerm_bundle_importer_fast:
    path: /importer/fast/{entity}
    controller: Musicjerm\Bundle\JermBundle\Controller\ImporterController::fastImport

jerm_bundle_importer_import:
    path: /importer/import/{entity}
    controller: Musicjerm\Bundle\JermBundle\Controller\ImporterController::importAction

jerm_bundle_importer_get_template:
    path: /importer/get_template/{entity}
    controller: Musicjerm\Bundle\JermBundle\Controller\ImporterController::getTemplateAction

jerm_bundle_clear_session:
    path: /session/clear
    controller: Musicjerm\Bundle\JermBundle\Controller\BaseController::clearSessionAction

jerm_bundle_notification_view:
    path: /notification/view/{id}
    controller: Musicjerm\Bundle\JermBundle\Controller\NotificationController::viewAction

jerm_bundle_notification_mark_read:
    path: /notification/mark_read
    controller: Musicjerm\Bundle\JermBundle\Controller\NotificationController::markReadAction

jerm_bundle_app_config:
    path: /admin/application
    controller: Musicjerm\Bundle\JermBundle\Controller\AppConfigController::indexAction

jerm_bundle_app_config_options:
    path: /admin/application/config_options
    controller: Musicjerm\Bundle\JermBundle\Controller\AppConfigController::configureOptions

jerm_bundle_app_git_update:
    path: /admin/application/git_update
    controller: Musicjerm\Bundle\JermBundle\Controller\AppConfigController::gitUpdate

jerm_bundle_app_composer_update:
    path: /admin/application/composer/{method}
    controller: Musicjerm\Bundle\JermBundle\Controller\AppConfigController::composerUpdate

jerm_bundle_app_doctrine_update:
    path: /admin/application/doctrine/{method}
    controller: Musicjerm\Bundle\JermBundle\Controller\AppConfigController::doctrineUpdate

jerm_bundle_app_cache:
    path: /admin/application/cache
    controller: Musicjerm\Bundle\JermBundle\Controller\AppConfigController::cacheAction